services:
  env:
    build:
      context: .
      dockerfile: Dockerfile
    image: ubuntu_env
    environment:
      HOST_UID: ${USER_ID:-1000}
      HOST_GID: ${GROUP_ID:-1000}
      HOST_USER: ${USER:-user}
      HOST_PASS: ${HOST_PASS}  # run_env.sh 経由で設定される。未設定時はsudo不可
      DISPLAY: ${DISPLAY_VAL}
    network_mode: host
    volumes:
      - type: bind
        source: "${HOME}/workspace"
        target: "/home/${USER:-user}/workspace"
      - type: bind
        source: "/tmp/.X11-unix"
        target: "/tmp/.X11-unix"
    tty: true
    stdin_open: true
